### ISSUE TITLE
Action doesn't return "fail" when GitLab has changes GitHub doesn't have

### ISSUE THREAD

**Issue by zuedev** [SvanBoxel/gitlab-mirror-and-ci-action#10]
**Action-logs:**
```
Switched to a new branch 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
pushing to master branch at https://gitlab.com/zuedev/*********
warning: redirecting to https://gitlab.com/zuedev/*********.git/
To https://gitlab.com/zuedev/*********
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'https://gitlab.com/zuedev/*********'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Triggered CI for branch master
Working with pipeline id #null
Poll timeout set to 10
Current pipeline status: null
Pipeline finished with status null
Fetching all GitLab pipeline jobs involved
jq: error (at <stdin>:0): Cannot index string with string "id"
Posting output from all GitLab pipeline jobs
Debug problems by unfolding stages/jobs above
```

**Comment by SvanBoxel** [comment]
Hi @zuedev, could you elaborate on the use case? It seems your pushing code to both GitLab and GitHub, while this Actions is designed in a way that code is only pushed by developers to GitHub, and then synced to GitLab.

**Comment by zuedev** [comment]
I believe my use case isn't the issue, as I have a hot GitHub repo and a cold GitLab mirror repo. No changes were pushed directly to the GitLab repo, yet due to some commit amending or history deletion on the GitHub-side, the two repos fell out of sync.

The reason I raised this issue is due to the fact that the GitHub action doesn't report that the push has failed. It marks the workflow as succeeding when it in fact failed to push the code due to some out-of-sync error. It would be a lot more helpful if it raised errors and failures to GitHub for increased visibility.

**Comment by SvanBoxel** [comment]
Gotcha, makes sense. I haven't thought of the conflicts that would arise with an altered history.

**Comment by mrlinnth** [comment]
I'm also facing the same issue.

Is there any workaround to overcome this?

**Comment by shahzebsiddiqui** [comment]
@SvanBoxel i noticed same issue see https://github.com/buildtesters/buildtest/issues/1112. I am inclined to believe something has changed in the release version 0.3 that has broken the mirroring job. My last job was 3 months ago

**Comment by SvanBoxel** [comment]
Release 0.3 was released about 9 months ago. But still it might be worth testing version 0.2 to see if the same problem still arrises.

**Comment by shahzebsiddiqui** [comment]
looks like version 0.2 works but not 0.3. I got the dependabot to notify me of upgrade so something went wrong in the latest release. IT would be nice to fix it for time being ill use the older version.

**Comment by shahzebsiddiqui** [comment]
i tested this out in https://github.com/buildtesters/buildtest/pull/1119 and i can see a pipeline triggered in our site local gitlab 

![Screen Shot 2022-06-28 at 5 09 12 PM](https://user-images.githubusercontent.com/12942230/176288360-926fa042-6584-47a3-ba88-c13764f245da.png)

**Comment by zuedev** [comment]
closing as stale
