### ISSUE TITLE
SSL certificate problem due to not updated trust pool

### ISSUE THREAD

**Issue by krauthosting** [SvanBoxel/gitlab-mirror-and-ci-action#12]
Got lately those errors which we assumed might have to due with non updated trust pools.
The new signing CA of Let's Encrypt is not in old CA trust pools like in EOLed Ubuntu 16.04.
Saw similar problems outside our fleet when folks are running still on unpatched Linux distros.

```
Run krauthosting/gitlab-mirror-and-ci-action@master
/usr/bin/docker run --name XXX --label YYY --workdir /github/workspace --rm -e GITLAB_HOSTNAME -e GITLAB_USERNAME -e GITLAB_PASSWORD -e GITLAB_PROJECT_ID -e GITHUB_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/atsw.de/atsw.de":"/github/workspace" YYY:XXX https://gitlab.domain.tld/path/repo
Switched to a new branch 'main'
Branch 'main' set up to track remote branch 'main' from 'origin'.
pushing to main branch at https://gitlab.domain.tld/path/repo
fatal: unable to access 'https://gitlab.domain.tld/path/repo/': SSL certificate problem: certificate has expired
Triggered CI for branch main
Working with pipeline id #
Poll timeout set to 10
Current pipeline status: null
Pipeline finished with status null
Fetching all GitLab pipeline jobs involved
Posting output from all GitLab pipeline jobs
Debug problems by unfolding stages/jobs above
```
@SvanBoxel Wonder what we can do for this project or if this is a known issue with GitHub actions and ubuntu-latest?

**Comment by krauthosting** [comment]
Digging just quick i assume it comes from using this:
https://hub.docker.com/r/makocchi/alpine-git-curl-jq
Quickly build a base image based on UBI8 from RedHat:
https://hub.docker.com/r/krauthosting/ubi8-git-curl-jq
A bit fat in size but better then a outdated Alpine image.

**Comment by krauthosting** [comment]
Let's discuss here first on image pick but fixed it for us now within:
https://github.com/krauthosting/gitlab-mirror-and-ci-action/tree/dockerfile

**Comment by SvanBoxel** [comment]
@krauthosting, you're totally right. Could you open a PR to address this problem?

Thank you so much! 🙇🏽

**Comment by shahzebsiddiqui** [comment]
i am also getting SSL certificate error through my workflow though i am using a fork of this repo

```
fatal: unable to access 'https://software.nersc.gov/siddiq90/buildtest/': SSL certificate problem: certificate has expired
```

I have recreated my gitlab token and added this in my secret but it is getting same issue.  I can confirm my token has the right permission so not sure why its not working.

Note this was working before and then all of sudden i get this expiration date so i recreated the token and got new password and updated my project. 
![Screen Shot 2021-10-14 at 5 47 19 PM](https://user-images.githubusercontent.com/12942230/137400175-c53ce6c4-2c1e-4c33-9942-930656cc626b.png)
s

**Comment by SvanBoxel** [comment]
Fixed in #13

**Comment by shahzebsiddiqui** [comment]
@SvanBoxel can you make a new release i see its merged in `master` it would be nice to have a tag release so its stable.

**Comment by SvanBoxel** [comment]
@shahzebsiddiqui Done. 👍🏽 https://github.com/SvanBoxel/gitlab-mirror-and-ci-action/releases/tag/0.3

**Comment by shahzebsiddiqui** [comment]
thank you
