### ISSUE TITLE
No action executed

### ISSUE THREAD

**Issue by david-hurtado-galac** [SvanBoxel/gitlab-mirror-and-ci-action#18]
When i call this action my job don´t excute nothing
I get this message: "Waiting for a runner to pick up this job..."

**Comment by SvanBoxel** [comment]
@david-hurtado-galac Could you share your workflow yml file?

**Comment by david-hurtado-galac** [comment]
This is the code
# This is a basic workflow to make a copy of this repo to GitLab
# to take a backup for all repo activities
name: Mirror on GitLab
on: [push]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/empresa/test/ticketsa.git"
      env:
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "git.galac"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN_GITGALAC }} 
        GITLAB_PROJECT_ID: "25694418" 
        GITHUB_TOKEN: ${{ secrets.FOR_GITLAB_TOKEN }}

**Comment by SvanBoxel** [comment]
There is a typo in there. You should use `ubuntu-latest` and not `ubuntu lastest`. 🙂

**Comment by david-hurtado-galac** [comment]
# Thank you SO MUCH!!!
 I'm a rookie...
