### ISSUE TITLE
Fork repositories

### ISSUE THREAD

**Issue by TriplEight** [SvanBoxel/gitlab-mirror-and-ci-action#2]
Does it mirror branches/PRs from forked repos to GitLab and return statuses for them?

**Comment by SvanBoxel** [comment]
Hi @TriplEight --  no, it doesn't take forked branches into consideration.

**Comment by TriplEight** [comment]
It's useless for opensource then :(

**Comment by SvanBoxel** [comment]
Do you have an example of an open-source project in GitLab that you want to sync to GitHub while still using GitLab CI?

**Comment by TriplEight** [comment]
We are doing the other way around: repo is on GitHub and all the PRs are being mirrored to GitLab for CI. 
Not sure about examples on what you've mentioned, but it's a pretty possible way to be opensource, have a decent (GitLab) CI and mirror the resulting code to GitHub for discoverability.
