### ISSUE TITLE
possible bug when namespace between github and gitlab differ

### ISSUE THREAD

**Issue by naromero77** [SvanBoxel/gitlab-mirror-and-ci-action#6]
Firstly, thank you for sharing your github action workflow script in the market place.

There may be a minor bug in this GitHub action when you have the same git repo name but different namespaces (usernames). For example, in my particular cases I have:
https://github.com/naromero77/rte-rrtmgp            (source)
https://software.nersc.gov/naromero/rte-rrtmgp   (mirror)
```
/usr/bin/docker run --name bb10364e20a41b3e45908f1d05c1dcc59fab_afdf04 --label 54bb10 --workdir /github/workspace --rm -e GITLAB_HOSTNAME -e GITLAB_USERNAME -e GITLAB_PASSWORD -e GITLAB_PROJECT_ID -e GITHUB_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/rte-rrtmgp/rte-rrtmgp":"/github/workspace" 54bb10:364e20a41b3e45908f1d05c1dcc59fab https://software.nersc.gov/naromero/rte-rrtmgp
Branch 'omp-45-cray' set up to track remote branch 'omp-45-cray' from 'origin'.
Switched to a new branch 'omp-45-cray'
pushing to naromero77/rte-rrtmgp/omp-45-cray branch at https://software.nersc.gov/naromero/rte-rrtmgp
error: src refspec naromero77/rte-rrtmgp/omp-45-cray does not match any.
error: failed to push some refs to 'https://software.nersc.gov/naromero/rte-rrtmgp'
Triggered CI for branch naromero77%2Frte-rrtmgp%2Fomp-45-cray
Working with pipeline id #null
Poll timeout set to 10
Current pipeline status: null
Pipeline finished with status null
Fetching all GitLab pipeline jobs involved
jq: error (at <stdin>:0): Cannot index string with string "id"
Posting output from all GitLab pipeline jobs
Debug problems by unfolding stages/jobs above
```

Is there a simple fix for this github action? Here is the workflow yaml file which I based on your template.
https://github.com/naromero77/rte-rrtmgp/tree/omp-45-cray/.github/workflows

**Comment by naromero77** [comment]
Possibly this commit caused problems?
https://github.com/SvanBoxel/gitlab-mirror-and-ci-action/commit/2ec0ff8c6140204c18a2802fa0061f945d6ffae8

**Comment by naromero77** [comment]
I can confirm that the bug is in master, because I can get version 0.2 to work.

**Comment by SvanBoxel** [comment]
Thanks for flagging @naromero77. I don't have time to work on a fix at the moment, but you're welcome to open a PR (or continue to use `0.2`).

**Comment by shahzebsiddiqui** [comment]
@SvanBoxel is it possible this action can be synced up with https://github.com/stenongithub/gitlab-mirror-and-ci-action seems like the fork has updated few things in the release https://github.com/stenongithub/gitlab-mirror-and-ci-action/releases that made this work for me. Perhaps talk to @stenongithub and see if he can send PR to this repo. Not sure if he/she wants to main this fork, we only see your action on github marketplace so it's relatively easy to find it.

I got my pipeline running see: https://github.com/buildtesters/buildtest/pull/602 it has a `gitlab-ci` CI job which seems to point to my gitlab job.

**Comment by SvanBoxel** [comment]
I'm very open to merge @stenongithub changes into this repository. Please feel free to open a PR.

**Comment by devantler** [comment]
@stenongithub has other issues. It works to push code to gitlab but it throws an error: pipeline_id is null, so we can't continue, so the actualt action shows as failed.

I will take a quick look at a PR to fix the issue with differing namespaces, as it seems thats the only issue with yours :-)
